FROM fivestarsos/commands-base:2.0.0

## commands are expected to be in `/code/commands`
## WORKDIR is already set to `/code`
COPY hello_world.py commands/hello_world.py

ENV PROJECT_NAME='commands-base-example'
