### this file was generated as an example project
### to add commands-base to your poetry project run:
### poetry add git+https://github.com/fivestars-os/commands-base@2.0.1

[tool.poetry]
name = "commands_base_example"
version = "0.1.0"
description = "Example of commands-base in a poetry-based project"
authors = ["Fivestars <dev@fivestars.com>"]

[tool.poetry.dependencies]
python = "^3.7"
commands-base = {git = "https://github.com/fivestars-os/commands-base", rev = "master"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
